---
defaults:
  - _self_
  - model: ???
  - optional data_process: ${model}
  - override hydra/launcher: torchrun
hydra:
  mode: MULTIRUN

pc_range: [0, -40, -3, 70.4, 40, 1]
voxel_size: [0.05, 0.05, 0.1]
class_names: [Car, Pedestrian, Cyclist]

dataset:
  _target_: pcdet.datasets.KittiDataset
  path: ../data/kitti
  class_names: ${class_names}
  info_paths: [kitti_infos_val.pkl, kitti_infos_train.pkl]
  item_names: [points]
  fov_points_only: true
  augmentor_cfg:
    - name: gt_sampling
      path: ${dataset.path}
      use_road_plane: false
      db_info_name: kitti_dbinfos_train.pkl
      prepare:
        filter_by_min_points: ['Car:5', 'Pedestrian:5', 'Cyclist:5']
        filter_by_difficulty: [-1]
      sample_groups: ['Car:20', 'Pedestrian:15', 'Cyclist:15']
      num_point_features: 4
      database_with_fakelidar: false
      remove_extra_width: [0.0, 0.0, 0.0]
      limit_whole_scene: true

    - name: random_world_flip
      along_axis_list: [x]

    - name: random_world_rotation
      world_rot_angle: [-0.78539816, 0.78539816]

    - name: random_world_scaling
      world_scale_range: [0.95, 1.05]
  pfe:
    _target_: pcdet.datasets.processor.PointFeatureEncoder
    name: absolute_coordinates_encoding
    used_feature_list: [x, y, z, intensity]
    src_feature_list: [x, y, z, intensity]
  processor_cfg:
    pc_range: ${pc_range}
    num_point_features: ${len:${..pfe.used_feature_list}}
    processor_list:
      # [test val, train val]
      - name: mask_points_and_boxes_outside_range
        remove_outside_boxes: true
      - name: shuffle_points
        shuffle_enabled: [false, true]
      - name: transform_points_to_voxels
        voxel_size: ${voxel_size}
        max_points_per_voxel: 5
        max_number_of_voxels: [40000, 16000]

log_dir: ${hydra:sweep.dir}
num_workers: 2
optional test: ???
optim:
  _target_: torch.optim.RAdam
scheduler:
  max_lr: 0.01
grad_max_norm: 10.0

MOMS: [0.95, 0.85]
PCT_START: 0.4
DIV_FACTOR: 10
DECAY_STEP_LIST: [35, 45]
LR_DECAY: 0.1
LR_CLIP: 0.0000001

LR_WARMUP: false
WARMUP_EPOCH: 1

GRAD_NORM_CLIP: 10
