---
name: OpenPCDet
channels:
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit=11.3
  - cudatoolkit-dev=11.3
  - pip
  - python=3.7
  - pytorch
  - wget
  # spconv requirements
  - fire
  - lark
  - portalocker
  - pybind11
  - requests
  # OpenPCDet requirements
  - easydict
  - gxx=10
  - numba
  - scikit-image
  - sharedarray
  - tensorboardx
  - tqdm
  # Linter
  - autoflake
  - black
  - clang-tools
  - cmake-format
  - cppcheck
  - flake8-bugbear
  - flake8-builtins
  - flake8-comprehensions
  - flake8-isort
  - flake8-logging-format
  - flake8-mutable
  - flake8-simplify
  - flake8-typing-imports
  - flake8-use-fstring
  - flake8-use-pathlib
  - isort
  - pep8-naming
  - yamllint
  - pip:
      - open3d  # Visualize
      - pyproject-flake8
      - spconv-cu113
