---
name: Thesis
channels:
  - pytorch
  - nvidia/label/cuda-11.6.2
  - conda-forge
dependencies:
  - cudatoolkit=11.6
  - pip
  - python=3.9
  - pytorch
  # OpenPCDet requirements
  - easydict
  - numba
  - scikit-image
  - sharedarray
  - tensorboard
  - tqdm
  # Linter
  - autoflake
  - black
  - clang-tools
  - cppcheck
  - cuda-toolkit
  - debugpy
  - gxx=11
  - isort
  - ninja
  - pylint
  - yamllint
  - pip:
      - open3d
