---
name: Thesis
channels:
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit=11.3
  - cudatoolkit-dev=11.3
  - pip
  - pytorch
  - wget
  # spconv requirements
  - fire
  - lark
  - portalocker
  - pybind11
  # Requirements
  - gxx=10
  - kornia
  - mayavi
  - numba
  - pillow
  - scipy
  - sharedarray
  - tensorboard
  - tqdm
  # Linter
  - autoflake
  - black
  - clang-tools
  - cppcheck
  - debugpy
  - flake8-bugbear
  - flake8-builtins
  - flake8-comprehensions
  - flake8-isort
  - flake8-logging-format
  - flake8-mutable
  - flake8-simplify
  - flake8-typing-imports
  - flake8-use-fstring
  - flake8-use-pathlib
  - isort
  - pep8-naming
  - yamllint
  - pip:
      - hydra-core
      - pyproject-flake8
      - spconv-cu113
