---
name: Thesis
channels:
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit=11.3
  - cudatoolkit-dev=11.3
  - pip
  - pytorch
  - wget
  # spconv requirements
  - fire
  - lark
  - portalocker
  - pybind11
  # OpenPCDet requirements
  - easydict
  - gxx=10
  - kornia
  - numba
  - scikit-image
  - sharedarray
  - tensorboard
  - tqdm
  # Linter
  - autoflake
  - black
  - clang-tools
  - cppcheck
  - debugpy
  - isort
  - pylint
  - yamllint
  - pip:
      - open3d  # Visualize
      - spconv-cu113
